# Generated by Django 5.0.3 on 2024-05-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='emp_age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empmodel',
            name='emp_position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
